# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nexmail 1.0 (28-jun-2017)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nexmail 1.0 (28-jun-2017)
	pod 'Fabric'
	pod 'Crashlytics'
end
